import Helper from "../helpers/EulerHelper"

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
class Problem2 {
    static solve(): number {
        let sum = 0;
        let it = Helper.fibonaccis();
        while (true) {
            let value = it.next().value;
            if (value > 4000000) break;
            if (value % 2 == 0) sum += value;
        }
        return sum;
    }
}

export default Problem2;